services:
    nginx:
        image: "nginx:1.29.1-alpine"
        restart: always
        working_dir: /app
        links:
            - php-fpm
        volumes:
            - ".:/app"
            - "./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
        ports:
            - "80:80"

    php-fpm:
        build: docker/php-fpm
        restart: always
        working_dir: /app
        links:
            - mariadb
        volumes:
            - ".:/app"
            - "./docker/php-fpm/php-overrides.ini:/usr/local/etc/php/conf.d/php-overrides.ini"
        environment:
            XDEBUG_MODE: "coverage"

    redis:
        image: "redis:8.2.2-alpine"
        environment:
            ALLOW_EMPTY_PASSWORD: "yes"

    mariadb:
        image: "mariadb:12.0.2"
        restart: always
        working_dir: /app
        volumes:
            - ".:/app"
            - "./docker/mariadb/data:/var/lib/mysql"
            - "./docker/mariadb/logs:/var/log/mysql"
            - "./docker/mariadb/conf:/etc/mysql"
        environment:
            MARIADB_ROOT_PASSWORD: "${MARIADB_ROOT_PASSWORD}"
            MARIADB_DATABASE: "${MARIADB_DATABASE}"
            MARIADB_USER: "${MARIADB_USER}"
            MARIADB_PASSWORD: "${MARIADB_PASSWORD}"
        ports:
            - "3306:3306"
