name: Docker Compose Test

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - "*"

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Login to Docker Hub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and test services
              run: |
                  docker-compose -f docker-compose.yml up --build -d

            -   name: Test Xdebug
                run: |
                    sleep 10 # Wait for the containers to fully initialize
                    XDEBUG_OUTPUT=$(curl -s http://localhost/index.php)
                    if [[ ! "$XDEBUG_OUTPUT" =~ "Xdebug" ]]; then
                      echo "Xdebug test failed. Not found in phpinfo() output."
                      exit 1
                    else
                      echo "Xdebug test successful."
                    fi

            -   name: Cleanup
                run: |
                    docker-compose -f docker-compose.yml down
